// <auto-generated />
using System;
using Mapping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MappingDemo.Data.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    partial class BooksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Mapping.Data.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<double>("StarRating")
                        .HasColumnType("REAL");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            DateOfBirth = new DateTime(1908, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ian",
                            LastName = "Flemming",
                            StarRating = 4.9100000000000001
                        },
                        new
                        {
                            AuthorId = 2,
                            DateOfBirth = new DateTime(1931, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "John",
                            LastName = "le Carré",
                            StarRating = 4.0099999999999998
                        });
                });

            modelBuilder.Entity("Mapping.Data.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Title = "Casino Royale",
                            Year = 1953
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            Title = "Live and Let Die",
                            Year = 1954
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 1,
                            Title = "Moonraker",
                            Year = 1955
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1,
                            Title = "Diamonds Are Forever",
                            Year = 1956
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 1,
                            Title = "From Russia, with Love",
                            Year = 1957
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 1,
                            Title = "Dr. No",
                            Year = 1958
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 2,
                            Title = "Call for the Dead",
                            Year = 1961
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 2,
                            Title = "A Murder of Quality",
                            Year = 1962
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 2,
                            Title = "The Spy Who Came In from the Cold",
                            Year = 1963
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 2,
                            Title = "The Looking Glass War",
                            Year = 1965
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 2,
                            Title = "Tinker Tailor Soldier Spy",
                            Year = 1974
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 2,
                            Title = "The Honourable Schoolboy",
                            Year = 1977
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 2,
                            Title = "Smiley's People",
                            Year = 1979
                        });
                });

            modelBuilder.Entity("Mapping.Data.Models.Book", b =>
                {
                    b.HasOne("Mapping.Data.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Mapping.Data.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
